stages:
  - build
  # 代码同步
  - sync

build:
  stage: build
  image: node:16.19.1
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - node_modules/
  script:
    - npm run pre
    - npm run build
  artifacts:
    paths:
      - build/
  # https://docs.gitlab.com/ee/ci/yaml/index.html#rules
  # 极狐GitLab中文文档：https://docs.gitlab.cn/jh/ci/yaml/index.html#rules
  rules:
    # PR 到 main 分支时预执行
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
    # PR 合并到 main 后执行、推送到 main 分支时
    - if: $CI_COMMIT_BRANCH == "main"
    # PR 合并到 main 后执行、推送到 main 分支时
    - if: $CI_COMMIT_BRANCH == "docusaurus"

# 嵌入
include:
  # 同步代码
  - /sync.yml
