stages:
  - build
  # 代码同步
  - sync

build:npm:
  stage: build
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - node_modules/
  script:
    - npm config set registry https://registry.npmmirror.com
    - echo $CI_PIPELINE_SOURCE
    - if [ $CI_PIPELINE_SOURCE == web ]; then
      npm install;
      fi
    - npm run build
    - mv build/ public/
  artifacts:
    expire_in: 1 week
    paths:
      - public/
  tags:
    - windows
  rules:
    - if: $CI_COMMIT_BRANCH == "build/windows"

# 嵌入
include:
  # 同步代码
  - /sync.yml
