stages:
  - build
  - publish
  # 代码同步
  - sync

build:
  stage: build
  image: node:16.19.1
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - node_modules/
  script:
    - npm run pre
    - npm run build
  artifacts:
    paths:
      - build/
  # https://docs.gitlab.com/ee/ci/yaml/index.html#rules
  # 极狐GitLab中文文档：https://docs.gitlab.cn/jh/ci/yaml/index.html#rules
  rules:
    # PR 到 main 分支时预执行
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
    # PR 合并到 main 后执行、推送到 main 分支时
    - if: $CI_COMMIT_BRANCH == "main"

publish-gitee-pages:
  stage: publish
  needs:
    - job: build
      artifacts: true
  image: bitnami/git:2.40.1
  script:
    - git config --global user.email $GITLAB_USER_EMAIL
    - git config --global user.name $GITLAB_USER_NAME
    - git config --global user.email
    - git config --global user.name
    - echo 当前分支：$CI_COMMIT_BRANCH
    - git checkout -b $CI_COMMIT_BRANCH
    - git add -f build/
    - git commit -m "发布 Gitee Pages"
    - git remote add gitee https://xuxiaowei-com-cn:$GITEE_PRIVATE_TOKEN@gitee.com/$CI_PROJECT_PATH.git
    - git push -f -u gitee $CI_COMMIT_BRANCH:pages
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

# 嵌入
include:
  # 同步代码
  - /sync.yml
