stages:
  - pages
  - docker:build
  - docker:deploy
  - sync

variables:
  DOCKER_TAG: 1.0.0

pages:
  stage: pages
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/node:20.12.0
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - node_modules/
  script:
    - npm run pre:npm
    - if [ $CI_SERVER_HOST == 'framagit.org' ]; then
      cat .vitepress/config.mts;
      sed -i 's#在 Gitee 上编辑此页面#在 FramaGit 上编辑#g' .vitepress/config.mts;
      sed -i 's#https://gitee.com/xuxiaowei-com-cn/gitlab-k8s/edit/main/#https://framagit.org/xuxiaowei-com-cn/gitlab-k8s/-/edit/main/#g' .vitepress/config.mts;
      cat .vitepress/config.mts;
      fi
    - npm run docs:build
    - cp -r .vitepress/dist/* public/
  artifacts:
    expire_in: 1 week
    paths:
      - public/
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $ENABLE_DOCS == "true"

docker:build:
  stage: docker:build
  image:
    name: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/xuxiaoweicomcn/kaniko-project-executor:v1.22.0-debug
    entrypoint: [""]
  needs:
    - job: pages
      artifacts: true
  before_script:
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"},\"https://index.docker.io/v1/\":{\"auth\":\"$(printf "%s:%s" ${DOCKER_USERNAME} "${DOCKER_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  script:
    - echo $DOCKER_TAG
    - /kaniko/executor version
    - /kaniko/executor --help
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --build-arg "CI_PIPELINE_URL=${CI_PIPELINE_URL}"
      --destination "${CI_REGISTRY_IMAGE}:${DOCKER_TAG}"
      --destination "${CI_REGISTRY_IMAGE}:${DOCKER_TAG}-${CI_PIPELINE_ID}"
      --destination "xuxiaoweicomcn/gitlab-k8s:${DOCKER_TAG}"
      --destination "xuxiaoweicomcn/gitlab-k8s:${DOCKER_TAG}-${CI_PIPELINE_ID}"
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $ENABLE_DOCS_DOCKER == "true"

docker:deploy:
  stage: docker:deploy
  needs:
    - job: docker:build
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/docker:26.1.1-cli
  variables:
    DOCKER_HOST: $DEPLOY_DOCKER_HOST
  script:
    - docker info
    - docker compose up -d
  environment: production
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $ENABLE_DOCS_DOCKER_DEPLOY == "true"
  tags:
    - lighthouse-docker

# 嵌入
include:
  # 同步代码
  - /sync.yml
