services:
  gitlab-k8s:
    image: registry.cn-qingdao.aliyuncs.com/xuxiaoweicomcn/gitlab-k8s:${DOCKER_TAG}-${CI_PIPELINE_ID}
    restart: always
    ports:
      - ${GITLAB_K8S_PORT:-45650}:80
    volumes:
      - /gitlab-k8s/logs:/var/log/nginx
    container_name: gitlab-k8s
